apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  config: |
    containerRuntimeExecutor: pns
    artifactRepository: 
      s3:
        bucket: argo-bucket
        endpoint: argo-artifacts.default:9000        
        insecure: true
        accessKeySecret:           
          name: argo-artifacts
          key: accesskey
        secretKeySecret:             
          name: argo-artifacts
          key: secretkey